on:
  pull_request:

name: Release
jobs:
        
  Build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - run: bash .cross_compile.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            dist/*
